development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: estadisticas_development
  pool:     5
  username: estadisticas
  password:
  template: template0

staging:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: estadisticas_staging
  pool:     5
  username: estadisticas
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: gestadisticas_test
  pool:     5
  username: estadisticas
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: estadisticas_production
  pool:     5
  username: estadisticas
  password:
  template: template0